# Generated by Django 5.0.6 on 2024-05-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('student', 'Student'), ('full', 'Full'), ('discount', 'Discount')], max_length=10, verbose_name='Категория плана'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость подписки'),
        ),
    ]
