# Generated by Django 5.0.6 on 2024-05-19 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_plan_plan_type_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('student', 'Student'), ('full', 'Full')], max_length=10, verbose_name='Категория плана'),
        ),
    ]
